from ._dtypes import EpisodeBatch, TimeStep, TimeStepBatch, StepType
from ._functions import (log_performance, obtain_evaluation_episodes, rollout,)
from ._torch_utils import (
    as_torch, as_torch_dict, compute_advantages, expand_var,
    filter_valids, flatten_batch, flatten_to_single_vector, global_device,
    NonLinearity, output_height_2d, output_width_2d, pad_to_last, prefer_gpu,
    product_of_gaussians, set_gpu_mode, soft_update_model, torch_to_np,
    update_module_params, compute_kl_divergence, compute_divergence_custom,
    correlation_coefficient, pad_and_stack, reset_module_parameters, 
    reset_optimizer,
    )

# yapf: enable
__all__ = [
    'EpisodeBatch',
    'TimeStep',
    'TimeStepBatch',
    'StepType',
    'log_performance',
    'obtain_evaluation_episodes',
    'rollout',
    'as_torch',
    'as_torch_dict',
    'compute_advantages',
    'expand_var',
    'filter_valids',
    'flatten_batch',
    'flatten_to_single_vector',
    'global_device',
    'NonLinearity',
    'output_height_2d',
    'output_width_2d',
    'pad_to_last',
    'prefer_gpu',
    'product_of_gaussians',
    'set_gpu_mode',
    'soft_update_model',
    'torch_to_np',
    'update_module_params',
    'compute_kl_divergence',
    'compute_divergence_custom',
    'correlation_coefficient',
    'pad_and_stack',
    'reset_module_parameters',
    'reset_optimizer',
]