"""This module creates a SAC-Discrete model in PyTorch."""
# yapf: disable
import copy
from collections import deque
import numpy as np
import torch
import torch.nn.functional as F
from garage import StepType
from garage.np.algos import RLAlgorithm
from garage.torch import as_torch_dict, global_device
from garage.experiment.deterministic import get_seed

from dowel import tabular

# For type hints (not necessary)
from ..experiment import Trainer

# Assuming CategoricalMLPPolicy and DiscreteMLPQFunction are available and suitable
# from src.policies import CategoricalMLPPolicy (or a similar discrete policy)
# from garage.torch.q_functions import DiscreteMLPQFunction (or a similar discrete Q-function)
# Users of this class will need to provide appropriate discrete policy and Q-function modules.

# yapf: enable


class SACDiscrete(RLAlgorithm):
    """A SAC-Discrete (Soft Actor-Critic for Discrete Actions) Model in Torch.

    This implementation is based on the paper "Soft Actor-Critic for Discrete
    Action Settings" by Petrenko et al. (https://arxiv.org/abs/1910.07207) and
    adapts the continuous SAC algorithm structure from `sac.py`.

    The user is expected to provide a policy that outputs a categorical
    distribution over discrete actions, and Q-functions that output Q-values
    for all discrete actions given an observation.

    Args:
        env_spec (EnvSpec): Environment specification.
        policy (garage.torch.policy.Policy): Policy/Actor for discrete actions.
            It should output a distribution (e.g., Categorical) from which
            action probabilities and log-probabilities can be obtained.
        qf1 (torch.nn.Module): QFunction/Critic.
            It should take observations and output Q-values for all discrete actions
            (e.g., a PyTorch module with forward pass `qf1(obs)` returning a tensor
            of shape [batch_size, num_actions]).
        qf2 (torch.nn.Module): Second QFunction/Critic, with the same interface as qf1.
        replay_buffer (ReplayBuffer): Stores transitions.
        max_episode_length_eval (int or None): Maximum length of episodes used
            for off-policy evaluation. If None, defaults to
            `env_spec.max_episode_length`.
        gradient_steps_n (int): Number of optimization steps that should
            occur before the training step is over and a new batch of
            transitions is collected by the sampler.
        fixed_alpha (float): The entropy/temperature to be used if temperature
            is not supposed to be learned.
        target_entropy (float): Target entropy for automatic entropy tuning.
            If None, the default heuristic `0.98 * log(|A|)` is used, where
            `|A|` is the number of discrete actions.
        initial_log_entropy (float): Initial log entropy/temperature
            coefficient if `fixed_alpha` is None.
        discount (float): Discount factor.
        buffer_batch_size (int): Batch size for training.
        min_buffer_size (int): Minimum transitions in replay buffer to start training.
        target_update_tau (float): Coefficient for Polyak averaging of target networks.
        policy_lr (float): Learning rate for policy optimizer.
        qf_lr (float): Learning rate for Q-function optimizers.
        reward_scale (float): Reward scale.
        optimizer (torch.optim.Optimizer): Optimizer class for all networks.
        num_evaluation_episodes (int): Number of episodes for evaluation.
        eval_env (Environment): Environment for evaluation. If None, a copy
            of the training environment is used.
    """
    name = 'SACDiscrete'

    def __init__(
            self,
            env_spec,
            policy,
            qf1,
            qf2,
            replay_buffer,
            *,  # Everything after this is numbers.
            discount=0.99,
            fixed_alpha=None,
            target_entropy=None,
            initial_log_entropy=0.,
            reward_scale=1.0,
            gradient_steps_n=1,
            buffer_batch_size=64,
            min_buffer_size=int(1e4),
            policy_lr=3e-4,
            qf_lr=3e-4,
            optimizer=torch.optim.Adam,
            target_update_tau=5e-3,
            num_evaluation_episodes=10,
            max_episode_length_eval=None):
        
        self.env_spec = env_spec
        self.policy = policy
        self._qf1 = qf1
        self._qf2 = qf2
        self.replay_buffer = replay_buffer

        self._action_dim = self.env_spec.action_space.n
        
        self._gradient_steps_n = gradient_steps_n
        self._min_buffer_size = min_buffer_size  # Sample size used to initialize the replay buffer with random actions generated by the initial policy.
        self._buffer_batch_size = buffer_batch_size
        self._policy_lr = policy_lr
        self._qf_lr = qf_lr
        self._initial_log_entropy = initial_log_entropy
        self._optimizer = optimizer
        self._tau = target_update_tau
        self._discount = discount
        self._reward_scale = reward_scale
        
        self._num_evaluation_episodes = num_evaluation_episodes
        self.max_episode_length = self.env_spec.max_episode_length
        self._max_episode_length_eval = self.env_spec.max_episode_length
        if max_episode_length_eval is not None:
            self._max_episode_length_eval = max_episode_length_eval
            
        # Target networks
        self._target_qf1 = copy.deepcopy(self._qf1)
        self._target_qf2 = copy.deepcopy(self._qf2)

        # Optimizers
        self._policy_optimizer = self._optimizer(self.policy.parameters(),
                                                 lr=self._policy_lr)
        self._qf1_optimizer = self._optimizer(self._qf1.parameters(),
                                              lr=self._qf_lr)
        self._qf2_optimizer = self._optimizer(self._qf2.parameters(),
                                              lr=self._qf_lr)

        # Automatic entropy coefficient tuning
        self._use_automatic_entropy_tuning = fixed_alpha is None
        self._fixed_alpha = fixed_alpha
        if self._use_automatic_entropy_tuning:
            if target_entropy is None:
                # Heuristic from the paper: 0.98 * log(|A|)
                self._target_entropy = 0.98 * np.log(self._action_dim)
            else:
                self._target_entropy = float(target_entropy)
            
            self._log_alpha = torch.tensor(self._initial_log_entropy,
                                           dtype=torch.float32,
                                           requires_grad=True) # Device set in to()
            self._alpha_optimizer = self._optimizer([self._log_alpha],
                                                    lr=self._policy_lr)
        else:
            self._log_alpha = torch.tensor(np.log(self._fixed_alpha),
                                           dtype=torch.float32,
                                           requires_grad=False) # Device set in to()
        
        self.episode_rewards = deque(maxlen=30)

        self.to(global_device())

    def train(self, trainer: Trainer):
        """Obtain samples and start actual training for each epoch.
        Args:
            trainer (Trainer): Gives the algorithm the access to
                :method:`~Trainer.step_epochs()`, which provides services
                such as snapshotting and sampler control.
        Returns:
            float: The average return in last epoch cycle.
        """
        last_performance = None
        for _ in trainer.step_epochs():
            trainer.enable_follower_logging = False
            for _ in range(trainer.train_args.itr_per_epoch):
                trainer.step_episode = trainer.obtain_samples(
                    trainer.step_itr)
                path_returns = []
                for path in trainer.step_episode:
                    obs = trainer.env_spec.get_inputs_for(
                        'follower', 'policy',
                        obs=path['observations'],
                        leader_act=path['env_infos']['leader_action']
                    ).detach().cpu().numpy()
                    next_obs = trainer.env_spec.get_inputs_for(
                        'follower', 'policy',
                        obs=path['next_observations'],
                        leader_act=path['next_leader_actions']
                    ).detach().cpu().numpy()
                    self.replay_buffer.add_transitions(
                        **dict(
                            observation=obs,
                            action=path['actions'],
                            reward=path['rewards'].reshape(-1, 1),
                            next_observation=next_obs,
                            terminal=np.array([
                                step_type == StepType.TERMINAL
                                for step_type in path['step_types']
                            ]).reshape(-1, 1)))
                    path_returns.append(sum(path['rewards']))
                assert len(path_returns) == len(trainer.step_episode)
                self.episode_rewards.append(np.mean(path_returns))
                if (self.replay_buffer.n_transitions_stored >=
                    self._min_buffer_size):
                    for _ in range(self._gradient_steps_n):
                        policy_loss, qf1_loss, qf2_loss, info = self.train_once()
                    trainer.enable_follower_logging = True
            trainer.step_itr += 1
            last_performance = trainer.evaluate_once(reset_env=True)
            if trainer.enable_follower_logging:
                self._log_statistics(policy_loss, qf1_loss, qf2_loss, info)
            tabular.record('TotalEnvSteps', trainer.total_env_steps)

        return np.mean(last_performance['AverageReturn'])

    def train_once(self):
        """Complete 1 training iteration of SAC.

        Args:
        Returns:
            torch.Tensor: loss from actor/policy network after optimization.
            torch.Tensor: loss from 1st q-function after optimization.
            torch.Tensor: loss from 2nd q-function after optimization.

        """
        if self.replay_buffer.n_transitions_stored >= self._min_buffer_size:
            samples = self.replay_buffer.sample_transitions(
                self._buffer_batch_size)
            samples = as_torch_dict(samples)
            for key, _ in samples.items():
                # Ensure action is long and correct shape after potential float conversion
                if key == 'action':
                    if not samples[key].dtype == torch.long:
                        samples[key] = samples[key].long()
                    if samples[key].ndim == 1:
                        samples[key] = samples[key].unsqueeze(-1)

            policy_loss, qf1_loss, qf2_loss, info = self.optimize_policy(samples)
            self._update_targets()

        return policy_loss, qf1_loss, qf2_loss, info
    
    def _get_log_alpha(self, samples_data=None):
        del samples_data
        return self._log_alpha

    def _temperature_objective(self, current_action_probs_detached, current_log_action_probs_detached, samples_data):
        """Compute the temperature/alpha coefficient loss."""
        alpha_loss = torch.tensor(0.0, device=global_device())
        if self._use_automatic_entropy_tuning:
            # For discrete SAC, entropy is -sum(p * log p)
            # The objective is to match this to target_entropy
            #entropy_term = -(current_action_probs_detached * torch.log(current_action_probs_detached + 1e-8)).sum(dim=-1)
            entropy_term = -(current_action_probs_detached * current_log_action_probs_detached).sum(dim=-1)
            alpha_loss = -(self._get_log_alpha(samples_data) * (entropy_term + self._target_entropy)).mean()
        return alpha_loss

    def _actor_objective(self, samples_data, current_action_probs, current_log_action_probs):
        """Compute the Policy/Actor loss."""
        obs = samples_data['observation']
        with torch.no_grad():
            alpha = self._get_log_alpha(samples_data).exp()

        with torch.no_grad():
            q1_all_actions = self._qf1(obs)
            q2_all_actions = self._qf2(obs)
            min_q_all_actions = torch.min(q1_all_actions, q2_all_actions)
        
        inside_term = alpha * current_log_action_probs - min_q_all_actions
        policy_objective = (current_action_probs * inside_term).sum(dim=-1).mean()
        
        return policy_objective

    def _critic_objective(self, samples_data):
        """Compute the Q-function/critic loss."""
        obs = samples_data['observation']
        actions = samples_data['action'] # Shape: (batch_size, 1), long type
        rewards = samples_data['reward'] 
        if rewards.ndim > 1 : rewards = rewards.squeeze(-1) # Ensure (batch_size,)
        rewards = rewards * self._reward_scale
        
        terminals = samples_data['terminal']
        if terminals.ndim > 1 : terminals = terminals.squeeze(-1) # Ensure (batch_size,)
        next_obs = samples_data['next_observation']

        with torch.no_grad():
            alpha = self._get_log_alpha(samples_data).exp()

        with torch.no_grad():
            next_dist, _ = self.policy(next_obs)
            next_action_probs = next_dist.probs
            next_log_action_probs = torch.nn.functional.log_softmax(next_dist.logits, 
                                                                    dim=-1)
            target_q1_next_all = self._target_qf1(next_obs)
            target_q2_next_all = self._target_qf2(next_obs)
            min_target_q_next_all = torch.min(target_q1_next_all, 
                                              target_q2_next_all)
            v_target_next = (
                next_action_probs * \
                (min_target_q_next_all - alpha * next_log_action_probs)
                ).sum(dim=-1)
            
            y_target = rewards + self._discount * (1. - terminals) * v_target_next # (batch_size,)

        q1_pred_all = self._qf1(obs)
        q2_pred_all = self._qf2(obs)
        
        # actions shape is (batch_size, 1)
        q1_pred = q1_pred_all.gather(1, actions).squeeze(-1) # (batch_size,)
        q2_pred = q2_pred_all.gather(1, actions).squeeze(-1) # (batch_size,)

        qf1_loss = F.mse_loss(q1_pred, y_target)
        qf2_loss = F.mse_loss(q2_pred, y_target)
        
        return qf1_loss, qf2_loss

    def _update_targets(self):
        """Update parameters in the target q-functions using Polyak averaging."""
        target_qfs = [self._target_qf1, self._target_qf2]
        qfs = [self._qf1, self._qf2]
        for target_qf, qf in zip(target_qfs, qfs):
            for t_param, param in zip(target_qf.parameters(), qf.parameters()):
                t_param.data.copy_(t_param.data * (1.0 - self._tau) +
                                   param.data * self._tau)

    def optimize_policy(self, samples_data):
        """Optimize the policy and alpha (if applicable)."""
        obs = samples_data['observation']
        qf1_loss, qf2_loss = self._critic_objective(samples_data)

        self._qf1_optimizer.zero_grad()
        qf1_loss.backward()
        self._qf1_optimizer.step()

        self._qf2_optimizer.zero_grad()
        qf2_loss.backward()
        self._qf2_optimizer.step()
        
        action_dist, _ = self.policy(obs)
        current_action_probs = action_dist.probs
        current_log_action_probs = torch.nn.functional.log_softmax(action_dist.logits, 
                                                                   dim=-1)

        policy_loss = self._actor_objective(samples_data, 
                                            current_action_probs, 
                                            current_log_action_probs)
        
        self._policy_optimizer.zero_grad()
        policy_loss.backward()
        policy_grad_norm = sum(
            p.grad.data.norm(2).item()**2 for p in self.policy.parameters() if p.grad is not None
            ) ** 0.5
        self._policy_optimizer.step()

        alpha_loss = None
        if self._use_automatic_entropy_tuning:
            alpha_loss = self._temperature_objective(current_action_probs.detach(), 
                                                     current_log_action_probs.detach(),
                                                     samples_data)
            self._alpha_optimizer.zero_grad()
            alpha_loss.backward()
            self._alpha_optimizer.step()

        policy_entropy = action_dist.entropy().mean().detach().item() if hasattr(action_dist, 'entropy') else 0.0

        info = {
            'policy_grad_norm': policy_grad_norm,
            'policy_entropy': policy_entropy
        }

        return policy_loss, qf1_loss, qf2_loss, info

    def _log_statistics(self, policy_loss, qf1_loss, qf2_loss, info, prefix='Follower'):
        """Log training statistics."""
        # Ensure values are scalars for logging
        log_policy_loss = policy_loss.item() if torch.is_tensor(policy_loss) else policy_loss
        log_qf1_loss = qf1_loss.item() if torch.is_tensor(qf1_loss) else qf1_loss
        log_qf2_loss = qf2_loss.item() if torch.is_tensor(qf2_loss) else qf2_loss
        policy_grad_norm = info.get('policy_grad_norm', None)
        if policy_grad_norm is not None:
            log_policy_grad_norm = policy_grad_norm.item() if torch.is_tensor(policy_grad_norm) else policy_grad_norm
        policy_entropy = info.get('policy_entropy', None)
        if policy_entropy is not None:
            log_policy_entropy = policy_entropy.item() if torch.is_tensor(policy_entropy) else policy_entropy
        
        with torch.no_grad():
            with tabular.prefix(prefix + '/'):
                tabular.record('AlphaTemperature/mean',
                            self._log_alpha.exp().mean().item())
                tabular.record('Policy/Loss', log_policy_loss)
                tabular.record('QF/{}'.format('Qf1Loss'), log_qf1_loss)
                tabular.record('QF/{}'.format('Qf2Loss'), log_qf2_loss)
                tabular.record('ReplayBuffer/buffer_size',
                            self.replay_buffer.n_transitions_stored)
                tabular.record('TrainAverageReturn',
                            np.mean(self.episode_rewards))
                
                if policy_grad_norm is not None:
                    tabular.record('Policy/GradNorm', log_policy_grad_norm)
                if policy_entropy is not None:
                    tabular.record('Policy/Entropy', log_policy_entropy)
                if self._use_automatic_entropy_tuning:
                    tabular.record('AlphaTemperature/TargetEntropy', self._target_entropy)

    @property
    def networks(self):
        """Return all the networks within the model."""
        nets = [self.policy, self._qf1, self._qf2, self._target_qf1, self._target_qf2]
        return [net for net in nets if net is not None]

    def to(self, device=None):
        """Put all the networks within the model on device."""
        if device is None:
            device = global_device()
        if not isinstance(device, torch.device):
            device = torch.device(device)

        for net in self.networks:
            net.to(device)
        
        if hasattr(self, '_log_alpha') and isinstance(self._log_alpha, torch.Tensor):
            self._log_alpha = self._log_alpha.to(device)
            if self._log_alpha.requires_grad: # If it was already requiring grad, keep it
                 self._log_alpha.requires_grad_(True)

                