"""Worker that "vectorizes" environments."""
import collections
import copy
import numpy as np

from ..utils import EpisodeBatch, StepType
from .default_worker import DefaultWorker
from ._functions import _apply_env_update


class VecWorker(DefaultWorker):
    """Worker with a single policy and multiple environments.

    Alternates between taking a single step in all environments and asking the
    policy for an action for every environment. This allows computing a batch
    of actions, which is generally much more efficient than computing a single
    action when using neural networks.

    Args:
        seed (int): The seed to use to intialize random number generators.
        max_episode_length (int or float): The maximum length of episodes which
            will be sampled. Can be (floating point) infinity.
        worker_number (int): The number of the worker this update is
            occurring in. This argument is used  set a different seed for
            each worker.
        n_envs (int): Number of environment copies to use.
    """

    DEFAULT_N_ENVS = 8

    def __init__(self,
                 *,
                 seed,
                 max_episode_length,
                 worker_number,
                 n_envs=DEFAULT_N_ENVS):
        super().__init__(seed=seed,
                         max_episode_length=max_episode_length,
                         worker_number=worker_number)
        self._n_envs = n_envs
        self._completed_episodes = []
        self._needs_agent_reset = True
        self._envs = [None] * n_envs
        self._agents = [None] * n_envs
        
        # yapf: disable
        self._completes = np.asarray([False] * n_envs)
        self._episode_lengths = [0 for _ in range(n_envs)]
        self._observations = [[] for _ in range(n_envs)]
        self._actions = [[] for _ in range(n_envs)]
        self._rewards = [[] for _ in range(n_envs)]
        self._step_types = [[] for _ in range(n_envs)]
        self._env_infos = [collections.defaultdict(list) for _ in range(n_envs)]
        self._agent_infos = [collections.defaultdict(list) for _ in range(n_envs)]
        self._episode_infos = [collections.defaultdict(list) for _ in range(n_envs)]
        # yapf: enable

    def update_agent(self, agent_update):
        """Update an agent, assuming it implements :class:`~Policy`.

        Args:
            agent_update (np.ndarray or dict or Policy): If a
                tuple, dict, or np.ndarray, these should be parameters to
                agent, which should have been generated by calling
                `Policy.get_param_values`. Alternatively, a policy itself. Note
                that other implementations of `Worker` may take different types
                for this parameter.
        """
        super().update_agent(agent_update)
        self._needs_agent_reset = True

    def update_env(self, env_update):
        """Update the environments.

        If passed a list (*inside* this list passed to the Sampler itself),
        distributes the environments across the "vectorization" dimension.

        Args:
            env_update(Environment or EnvUpdate or None): The environment to
                replace the existing env with. Note that other implementations
                of `Worker` may take different types for this parameter.

        Raises:
            TypeError: If env_update is not one of the documented types.
            ValueError: If the wrong number of updates is passed.
        """
        if isinstance(env_update, list):
            if len(env_update) != self._n_envs:
                raise ValueError('If separate environments are passed for '
                                 'each worker, there must be exactly n_envs '
                                 '({}) environments, but received {} '
                                 'environments.'.format(
                                     self._n_envs, len(env_update)))
        elif env_update is not None:
            env_update = [
                copy.deepcopy(env_update) for _ in range(self._n_envs)
            ]
        if env_update:
            for env_index, env_up in enumerate(env_update):
                self._envs[env_index], up = _apply_env_update(
                    self._envs[env_index], env_up)

    def start_episode(self, 
                      init_state=None, 
                      init_follower_action=None,
                      deterministic_l=False,
                      deterministic_f=False,
                      explorate_l=False,
                      explorate_f=False,
                      zero_action_l=False,
                      zero_action_f=False):
        """Begin a new episode."""
        n = self._n_envs
        if self._needs_agent_reset:
            self.agent.reset([True] * n)
        obs_list, episode_infos_list = [], []
        for env in self._envs:
            obs, episode_info = env.reset(init_state)
            obs_list.append(obs)
            episode_info['init_state'] = init_state
            episode_info['init_follower_action'] = init_follower_action
            episode_infos_list.append(episode_info)
        prev_obs = np.asarray(obs_list)
        acts, agent_infos = self.agent.get_actions(
            prev_obs,
            deterministic_leader=deterministic_l, 
            deterministic_follower=deterministic_f,
            explorate_leader=explorate_l,
            explorate_follower=explorate_f,
            zero_leader=zero_action_l,
            zero_follower=zero_action_f,
        )  # acts: List[ndarray]. acts[0].shape=(n_envs, leader_action_dim), acts[1].shape=(n_envs, follower_action_dim)
        for i in range(n):
            if init_follower_action is not None:
                if self._envs[i].spec.follower_action_space.contains(init_follower_action):
                    acts[1][i] = init_follower_action
                else:
                    raise ValueError('The init_follower_action is not contained in the follower action space.')
            for k in episode_infos_list[i].keys():
                self._episode_infos[i][k].append(episode_infos_list[i][k])
        # Spaceholder for previous observation, action, and agent_info
        self._prev_obs = prev_obs.copy()  # shape = (n_envs, obs_dim)
        self._prev_acts = [acts[0].copy(), acts[1].copy()]  # [np.ndarray (n_envs, leader_action_dim), np.ndarray (n_envs, follower_action_dim)], cannot be converted to np.array because the shapes of leader_action and follower_action may differ
        # Buffer for current episode
        self._episode_lengths = [0 for _ in range(n)]
        self._observations = [[prev_obs[i]] for i in range(n)]
        self._actions = [[] for _ in range(n)]
        self._rewards = [[] for _ in range(n)]
        self._step_types = [[] for _ in range(n)]
        self._env_infos = [collections.defaultdict(list) for _ in range(n)]
        self._agent_infos = [{k: [v[i]] for k, v in agent_infos.items()} for i in range(n)]

        self._completes = np.asarray([False] * n)
        self._needs_agent_reset = False

    def _gather_episode(self, 
                        env_id, 
                        last_leader_action):
        assert 0 < self._episode_lengths[
            env_id] <= self._max_episode_length
        env_infos = self._env_infos[env_id]
        agent_infos = self._agent_infos[env_id]
        episode_infos = self._episode_infos[env_id]
        for k, v in env_infos.items():
            env_infos[k] = np.asarray(v)
        for k, v in agent_infos.items():
            agent_infos[k] = np.asarray(v)[:-1]
        for k, v in episode_infos.items():
            episode_infos[k] = np.asarray(v)
        eps = EpisodeBatch(
            env_spec=self._envs[env_id].spec,
            episode_infos=dict(episode_infos),
            observations=np.asarray(self._observations[env_id][:-1]),
            last_observations=np.asarray(self._observations[env_id][-1:]),
            last_leader_actions=np.asarray([last_leader_action]),
            actions=np.asarray(self._actions[env_id]),
            rewards=np.asarray(self._rewards[env_id]),
            step_types=np.asarray(self._step_types[env_id],
                                  dtype=StepType),
            env_infos=dict(env_infos),
            agent_infos=dict(agent_infos),
            lengths=np.asarray([self._episode_lengths[env_id]],
                               dtype='l'))

        self._completed_episodes.append(eps)
        self._observations[env_id] = []
        self._actions[env_id] = []
        self._rewards[env_id] = []
        self._step_types[env_id] = []
        self._episode_lengths[env_id] = 0
        self._prev_obs[env_id] = self._envs[env_id].reset()[0]
        self._env_infos[env_id] = collections.defaultdict(list)
        self._agent_infos[env_id] = collections.defaultdict(list)
        self._episode_infos[env_id] = collections.defaultdict(list)

    def step_episode(self, 
                     deterministic_l=False,
                     deterministic_f=False,
                     explorate_l=False,
                     explorate_f=False,
                     zero_action_l=False,
                     zero_action_f=False):
        """Take a single time-step in the current episode.

        Returns:
            bool: True iff at least one of the episodes was completed.
        """
        finished = False
        env_steps = [None] * self._n_envs
        not_comp_i = np.where(~self._completes)[0]
        leader_actions = self._prev_acts[0][not_comp_i]
        follower_actions = self._prev_acts[1][not_comp_i]

        for i, la, fa in zip(not_comp_i, leader_actions, follower_actions):
            action = [la, fa]
            if self._episode_lengths[i] < self._max_episode_length:
                env_steps[i] = self._envs[i].step(action)  # Step each environment
        for i in not_comp_i:
            if env_steps[i] is not None:
                es = env_steps[i]
                # append previous step information
                self._observations[i].append(es.observation)
                self._rewards[i].append(es.reward)
                self._actions[i].append(es.action)
                self._step_types[i].append(es.step_type)
                es.env_info['time_step'] = self._episode_lengths[i]
                for k, v in es.env_info.items():
                    self._env_infos[i][k].append(v)
                self._prev_obs[i] = es.observation

        next_obs = self._prev_obs[not_comp_i]
        next_acts, agent_info = self.agent.get_actions(
            next_obs,
            deterministic_leader=deterministic_l,
            deterministic_follower=deterministic_f,
            explorate_leader=explorate_l,
            explorate_follower=explorate_f,
            zero_leader=zero_action_l,
            zero_follower=zero_action_f
        )
        self._prev_acts[0][not_comp_i] = next_acts[0]
        self._prev_acts[1][not_comp_i] = next_acts[1]
        for k, v in agent_info.items():
            for i in range(len(not_comp_i)):
                self._agent_infos[not_comp_i[i]][k].append(v[i])
        for i in not_comp_i:
            self._episode_lengths[i] += 1
            if self._episode_lengths[i] >= self._max_episode_length or env_steps[i].last:
                self._gather_episode(i, self._prev_acts[0][i].copy())
                self._completes[i] = True
        if any(self._completes):
            self.agent.reset(self._completes)
        finished = all(self._completes)
        return finished

    def collect_episode(self):
        """Collect all completed episodes.

        Returns:
            EpisodeBatch: A batch of the episodes completed since the last call
                to collect_episode().

        """
        if len(self._completed_episodes) == 1:
            result = self._completed_episodes[0]
        else:
            result = EpisodeBatch.concatenate(*self._completed_episodes)
        self._completed_episodes = []
        return result

    def shutdown(self):
        """Close the worker's environments."""
        for env in self._envs:
            env.close()
